[platformio]
default_envs = axistx_promicro

[env]
framework = arduino
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
build_flags =
    -DFIRMWARE_VERSION=\"0.1.0\"

[env:axistx_promicro]
platform = atmelavr
board = sparkfun_promicro16
build_flags =
    ${env.build_flags}
    -DBOARD_PROMICRO
    -DHAS_OLED